version: '3'
services:
  web:
    build: .
    ports:
      - "8000:3000"
    volumes:
      - .:/usr/src/app
      - log_volume:/usr/src/app/logs
    links:
      - redis
      - mysql
      - mongo
    environment:
      - VIRTUAL_HOST=api.developers.dev

  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redispass
    volumes:
      - redis_volume:/bitnami

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD : root
      MYSQL_DATABASE: developers
    volumes:
      - mysql_volume:/var/lib/mysql

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_volume:/data/db

volumes:
  log_volume: {}
  mysql_volume: {}
  mongo_volume: {}
  redis_volume: {}